# -*- coding: utf-8 -*-
"""EDA_Wish_Summer_Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFaidlgvSGC4lHC57msJXkJuaAOfMKBD
"""

import pandas as pd

df = pd.read_csv('/content/summer-products-with-rating-and-performance_2020-08.csv')

df.head()

df.columns

df = df[['title_orig', 'price', 'retail_price',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'merchant_rating_count', 'merchant_rating']]

numerical_col = df.describe().columns

categorical_col = [i for i in cols if i not in numerical_col]

df.fillna(" ")

df.isna().sum()

df.loc[df['product_color'].isna(), 'product_color'] = ""
df.loc[df['product_variation_size_id'].isna(), 'product_variation_size_id'] = ""
df.loc[df['has_urgency_banner'].isna(), 'has_urgency_banner'] = ""

import os

username = "italofvaz" # insira o seu nome de usuário do git
os.environ["GITHUB_USER"] = username

!git config --global user.name "${GITHUB_USER}"

from getpass import getpass

usermail = getpass()
os.environ["GITHUB_MAIL"] = usermail

!git config --global user.email "${GITHUB_MAIL}"

usertoken = getpass()
os.environ["GITHUB_TOKEN"] = usertoken

!git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/italofvaz/EDA_Wish_Sales.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/EDA_Wish_Sales/

!git add .

!git commit -m "first analysis"

!git push origin main